### ISSUE TITLE
use `textwidth` to measure the length of a unicode strings? 

### ISSUE THREAD

**Issue by YongHee-Kim** [FedeClaudi/Term.jl#10]
Hi! Thanks for developing the `Term.jl` I'm very excited and looking forward to the official release 😃 

https://github.com/FedeClaudi/Term.jl/blob/083b6e66dce6840a9e38412cdc10046335e8f874/src/measure.jl#L27
If we use `length` we will get a wrong number of columns needed to print a unicode string
```julia
julia> using Term
julia> s1 = "나랏말싸미 듕귁에 달아"
julia> s2 = "こんにちは(わ)"
```
![image](https://user-images.githubusercontent.com/7087745/156925666-d554d52c-dd74-4186-8767-9d9eb52aa95e.png)

But with `textwidth` we get the correct number of columns for [most of times ](https://github.com/JuliaLang/julia/issues/31075)
![image](https://user-images.githubusercontent.com/7087745/156925731-d09c49d6-2cef-45a0-9856-bd0b4a0f3de7.png)

**Comment by FedeClaudi** [comment]
Thanks for spotting that! I've added that in, it seems to work correctly now: e72282c71fac50bc37e1920939171722d2cdc971

Let me know what else you come across, I appreciate you testing Term.jl before its official release!
