### ISSUE TITLE
Testing broken (again) on some terminal sizes

### ISSUE THREAD

**Issue by t-bltg** [FedeClaudi/Term.jl#112]
Running tests against latest master 8324efaa22ed0a972047eab4a583aee152a13dc0:

```julia
julia> using Pkg; @show displaysize(stdout); Pkg.test("Term")
displaysize(stdout) = (46, 147)

[...]
Running: '08_test_panel.jl' 
Test Summary:           | Pass  Total
Panel - no content  |   54     54
Test Summary:                | Pass  Total
Panel - fit basic shape  |   36     36
Test Summary:             | Pass  Total
Panel - fit overflow  |    4      4
Test Summary:              | Pass  Total
PANEL - fit - measure  |  138    138
PANEL - nofit - measure: Test Failed at [...]/Term.jl/test/__test_utils.jl:65
  Expression: p.measure.h == h
   Evaluated: 6 == 5
Stacktrace:
 [1] macro expansion
   @ [...]/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
 [2] testpanel(p::Panel, w::Int64, h::Int64)
   @ Main [...]//Term.jl/test/__test_utils.jl:65
```

**Comment by FedeClaudi** [comment]
damn...

I don't understand why that particular test is failing. Sometimes I run it and it comes out `5`, sometimes `6`... I don't get it...
I think I should put a lot more effort into making more robust, clear and reliable tests... 
After this next big release I will have to step back from Term for a while but this will be the next main thing to focus on.

If it's a problem for now just disable that test, it's for a very corner case anyway..

**Comment by t-bltg** [comment]
> If it's a problem for now just disable that test, it's for a very corner case anyway..

I'm not resizing my terminal for now instead ;)

**Comment by FedeClaudi** [comment]
fair...

besides this we're ready for the release of version 1.0 - unless you had something else you wanted to tweak?

**Comment by t-bltg** [comment]
@FedeClaudi, I'm onto a fix. I'm also renaming `truncate` since shadowing std lib functions is very confusing :/

**Comment by FedeClaudi** [comment]
> 'm also renaming truncate

Good call. 

Sounds good, thank you. I don't think I'll have time to review it today but first thing tomorrow.
