### ISSUE TITLE
ProgressBar Issues

### ISSUE THREAD

**Issue by nathanrboyer** [FedeClaudi/Term.jl#123]
MWE:
*Adjust inputs to slightly strain your machine.*
*I am running in VSCode for Windows.*
```julia
using GLMakie, Term, Term.Progress

f1(x) = for i in 1:x; println(i); end; sleep(4)
f2(x) = collect(1:x)
f3(x) = lines(1:x, 1:x)

function main(x, y, z)
    progressbar = ProgressBar(; columns=:minimal, columns_kwargs = Dict(:SpinnerColumn => Dict(:spinnertype => :circle)))
    output = with(progressbar) do
        job1 = addjob!(progressbar, description = "Running Function 1")
        start!(job1)
        yield()
        sleep(0.001)
        f1(x)
        stop!(job1)

        job2 = addjob!(progressbar, description = "Running Function 2")
        start!(job2)
        yield()
        sleep(0.001)
        f2(y)
        stop!(job2)

        job3 = addjob!(progressbar, description = "Running Function 3")
        start!(job3)
        yield()
        sleep(0.001)
        f3(z)
        stop!(job3)

        "Output"
    end
    return output
end

main(40, 1E9, 1E5)
```

1. `job1` spinner appears but does not spin. 
2. `job1` checkmark does not appear until both `job1` and `job2` are complete.
3. `job2` spinner does not appear. The text and checkmark only appear once finished.
4. `job3` does not appear at all including text, spinner, and checkmark.
5.  The output text lines above the top of the REPL window are deleted.
6. `output` does not appear.

*Same behavior whether I use `yield()` or `sleep(0.001)`.*
![image](https://user-images.githubusercontent.com/65452054/174856477-98099f3a-e572-480d-9f6e-86d0a098a94a.png)

**Comment by FedeClaudi** [comment]
Hi, 

Sorry for the delay in getting back to you. 
There were a few issues with threading and the timing between when jobs were stopped and the progress bar display updated. It works fine in the development branch with this code:

```julia
using Term, Term.Progress

f1(x) = for i in 1:x; println(i); end; sleep(0)
f2(x) = collect(1:x)
f3(x) = collect(1:x).^2

function main(x, y, z)
    progressbar = ProgressBar(; columns=:minimal,  columns_kwargs = Dict(:SpinnerColumn => Dict(:spinnertype => :circle)))
    output = with(progressbar) do
        job1 = addjob!(progressbar, description = "Running Function 1")
        f1(x)
        stop!(job1)

        job2 = addjob!(progressbar, description = "Running Function 2")
        f2(y)
        stop!(job2)

        job3 = addjob!(progressbar, description = "Running Function 3")
        f3(z)
        stop!(job3)

        "Output"
        println("Output2")
    end
    return output
end




main(50, 1E9, 1E5)
```
https://user-images.githubusercontent.com/17436313/182002672-13501e69-8f8e-4f29-9314-9eedf13ff8f7.mov

I think don't understand 5: if I say call `f1` with `x=100` so that a few lines are scrolled above the terminal's height, I can scroll back up and find them.
For issue 6, that was a bug due to a typo, will be fixed in the next release

**Comment by nathanrboyer** [comment]
Great, thanks. I think issue #5 I was having is not a term issue.

**Comment by nathanrboyer** [comment]
![image](https://user-images.githubusercontent.com/65452054/182904082-d0c39e0f-25ae-4fab-b62b-0ffc87806211.png)
When I test your code on the Dev version (changing `Term.Progress` to `Term.progress`), I don't see any progress bars until everything completes:
![image](https://user-images.githubusercontent.com/65452054/182902227-f6193da7-f8cb-4e15-8f2b-5167cefd96d4.png)
![image](https://user-images.githubusercontent.com/65452054/182902274-398b794e-351a-4596-9e63-da4fc34d502a.png)

When I test my code on the Dev version (changing `Term.Progress` to `Term.progress`), I see the following static steps (no spinning):
![image](https://user-images.githubusercontent.com/65452054/182903499-e3967eac-7e99-4ca2-b9a8-22bc6209985a.png)
![image](https://user-images.githubusercontent.com/65452054/182903620-6d4a70f4-de2f-437e-b06a-dd0d12ba063f.png)
![image](https://user-images.githubusercontent.com/65452054/182903803-efc8e485-2e65-46c5-93a3-caac253329e9.png)
![image](https://user-images.githubusercontent.com/65452054/182903540-17158156-fb9f-48c1-aa01-ad03b253f949.png)

**Comment by nathanrboyer** [comment]
I still get the same behavior described in my first post on the master branch.

With your code on the 1.0.3 branch, I get the following static steps:
![image](https://user-images.githubusercontent.com/65452054/182907666-6217296e-825e-46e9-bec4-6a7b4fa86054.png)
![image](https://user-images.githubusercontent.com/65452054/182907838-ab38e721-5fe8-4cd5-a575-79916ef1bfa2.png)
![image](https://user-images.githubusercontent.com/65452054/182907864-357b02fc-f96c-4f77-9a27-45082c8d38ea.png)

With my code on the 1.0.3 branch, I get the following static steps:
![image](https://user-images.githubusercontent.com/65452054/182908166-c928b640-af07-4e09-aaed-2b7812fd7f52.png)
![image](https://user-images.githubusercontent.com/65452054/182909377-eb5b5fd0-242a-4189-8cc0-8fcee0bf23e1.png)
![image](https://user-images.githubusercontent.com/65452054/182909459-8e843423-1835-4e17-92f8-07b58451e85a.png)

There is no spinning at any point and my terminal text is still cut off when I scroll back up:
![image](https://user-images.githubusercontent.com/65452054/182909742-5b1c6d1d-8048-4c9e-9368-f6e5d35cc6c7.png)

**Comment by FedeClaudi** [comment]
I'll close this for now as new versions have been released and ProgressBar has been re-worked somewhat. Please get in touch if it's still an issue.
