### ISSUE TITLE
`termshow(::DataType)` fails

### ISSUE THREAD

**Issue by gdalle** [FedeClaudi/Term.jl#129]
![Screenshot from 2022-06-27 12-37-33](https://user-images.githubusercontent.com/22795598/175922975-4f07ad75-9917-4c08-8b78-ceeb0cfdb328.png)

I suppose it is a rather niche bug but I sometimes want to display `DataType`s in the REPL, and I can't when `install_term_repr()` has been run.

**Comment by FedeClaudi** [comment]
Hi, https://github.com/FedeClaudi/Term.jl/pull/128 should've fixed this. If you update Term to v1.0.2 it should work.

**Comment by gdalle** [comment]
Yes it works, thanks!
