### ISSUE TITLE
Combining Term with Test fails to render errors

### ISSUE THREAD

**Issue by gdalle** [FedeClaudi/Term.jl#130]
![Screenshot from 2022-06-27 12-49-56](https://user-images.githubusercontent.com/22795598/175925008-2992dd62-ffda-4c5f-943e-e092130a9de2.png)

Not sure what is going on here, is this supposed to happen?

**Comment by FedeClaudi** [comment]
Hi, https://github.com/FedeClaudi/Term.jl/pull/128 should've fixed this. If you update Term to v1.0.2 it should work.

**Comment by gdalle** [comment]
Yes it works, thanks!
