### ISSUE TITLE
Nesting Links & Colors

### ISSUE THREAD

**Issue by jeremiahpslewis** [FedeClaudi/Term.jl#132]
Using a link in a colored field causes the color to be dropped (in Pluto, but not in the command line). Probably not directly a Term.jl issue, but I can't place my finger on the package 'at fault'. ;)

```Julia
using Term
test_link = Term.creat_link("https://google.com", "test string")
println(@red(test_link))
```

**Comment by FedeClaudi** [comment]
Hey, sorry for the delay in getting back with this. 

Unfortunately, links are treated differently by different terminals/systems. For instance the example above works fine in iTerm but not VSCode's built-in terminal: there the link just doesn't work. As such. I don't think there's much I can do here. 

At least it's just the color that is lost and the link is still functional 😁
