### ISSUE TITLE
Specify branch order in Tree

### ISSUE THREAD

**Issue by peng1999** [FedeClaudi/Term.jl#139]
Currently `Term.Trees.Tree` only accepts `Dict` to construct a tree. So we cannot control the order of the branches because `Dict` is unordered.

This is what I get in Julia 1.7.3, Term v1.0.2:

```julia
julia> Tree(Dict(1 => nothing, 2 => Dict(4 => nothing), 3 => nothing))
 tree
━━━━━━
  │
  ├── 2
  │   └── 4
  │
  ├── 3
  └── 1
```

But what I want is

```
 tree
━━━━━━
  │
  ├── 1
  ├── 2 
  │   └── 4
  └── 3
```

I tried passing `Vector` instead of `Dict` but nested Vector seems not working as expected.

So is there a way to solve this?

**Comment by FedeClaudi** [comment]
Hi,

Sure, `OrderedDict` Can be used to specify branches order.

**Comment by peng1999** [comment]
Sorry for not finding #68. I proposed #140 to make the feature more discoverable.

**Comment by peng1999** [comment]
@FedeClaudi 
Hi,
I tried `OrderedDict` but it does not work as expected:

```julia
julia> Tree(OrderedDict(1 => nothing, 2 => OrderedDict(3 => nothing)))
 tree
━━━━━━
  │
  ├── 2
  │   └── 3
  │
  └── 1
```

Is it possible to construct the following output?

```
 tree
━━━━━━
  │
  ├── 1
  └── 2
      └── 3
```

**Comment by FedeClaudi** [comment]
Hey, 

The problem is that `2` is a `node` of the tree (i.e. it has a sub-tree) while `1` is a leaf (it doesn't have subtrees). `OrderedDict` can be used to set the order within nodes or within leaves, but trees are rendered by first showing all nodes and then all leaves.

If you change the tree's contents to have two nodes it works as expected:

```julia
t = Tree(
    OrderedDict(
        3 => OrderedDict(
            3 => 8,  
            1 => "a"
        ), 
        2 => OrderedDict(
            3 => 8,  
            1 => "a"
        )
    )
)

```

```
 tree         
━━━━━━        
  │           
  ├── 3       
  │   ├── 3: 8
  │   └── 1: a
  └── 2       
      ├── 3: 8
      └── 1: a
```


Would this be okay with your use-case, or do you need complete control on the order?

**Comment by FedeClaudi** [comment]
Got it, okay.

Took a bit of work but now you can:

```julia
t = Tree(
    OrderedDict(
    2 => 1,
    3 => OrderedDict(
            4 => 2,
            "a" => 2,  
            "b" => 1
        ), 

    )
)

```

```

 tree         
━━━━━━        
  │           
  ├── 2: 1    
  └── 3       
      ├── 4: 2
      ├── a: 2
      └── b: 1

```

It will come out with the next release (can't guarantee it will be very soon, but within a 2/3 weeks)
