### ISSUE TITLE
messed up styles with logs

### ISSUE THREAD

**Issue by AbhimanyuAryan** [FedeClaudi/Term.jl#154]
I think something is messing up the styles of my Genie/Stipple logs

With Term.jl 
![Screenshot 2022-08-31 at 12 21 53 PM](https://user-images.githubusercontent.com/8083613/187612981-e1d5c4e9-f111-4e0d-a726-1055471c0700.png)
![Screenshot 2022-08-31 at 12 22 12 PM](https://user-images.githubusercontent.com/8083613/187612974-c180b9d6-44b3-48a8-99b3-98f568dc5e76.png)

Without Term.jl

![Screenshot 2022-08-31 at 12 23 38 PM](https://user-images.githubusercontent.com/8083613/187613018-a1041b3d-34a1-410f-a2e7-fd49d32f1050.png)

Code to reproduce this:

https://github.com/GenieFramework/StippleDemos/tree/master/BasicExamples/CSVUploadProcess

```
$ julia --project 
pkg> instantiate
julia> include("CSVUploadProcess.jl")
```

**Comment by AbhimanyuAryan** [comment]
boxes don't are messing up styles I believe

buggy code you can test to reproduce 

```julia
@with_repr struct OrderedPair
       x::Real
       y::Real
       z::Real
       OrderedPair(x,y) = x > y ? error("out of order") : new(x,y)
end

OrderedPair(1,2)
```


![Screenshot 2022-09-04 at 10 16 17 PM](https://user-images.githubusercontent.com/8083613/188324365-3e6d9ff4-7b85-46f1-a5f2-c923847c1dd8.png)
![Screenshot 2022-09-04 at 10 16 26 PM](https://user-images.githubusercontent.com/8083613/188324368-e658670c-3d66-4811-8a4d-5f6a09e04ed5.png)

![Screenshot 2022-09-04 at 10 16 34 PM](https://user-images.githubusercontent.com/8083613/188324372-09c57376-0314-4520-b342-32c9e9cd2ebc.png)

**Comment by FedeClaudi** [comment]
Hey, is this with the latest version? This should be better now compared to the previous release (although not perfect yet)

**Comment by AbhimanyuAryan** [comment]
Will check and let you know 💜

**Comment by AbhimanyuAryan** [comment]
yes those are the issues with 1.0.4 
If possible please try to run the demo I provided to see it yourself

**Comment by AbhimanyuAryan** [comment]
@FedeClaudi is this indentation intended? 

<img width="908" alt="Screenshot 2022-09-19 at 5 16 25 PM" src="https://user-images.githubusercontent.com/8083613/191010467-d2f2b9b9-4b23-4a28-8a1a-57d5d6ae36b3.png">

**Comment by FedeClaudi** [comment]
I think so, but perhaps it would look better without?

**Comment by AbhimanyuAryan** [comment]
@FedeClaudi I would like to tag a friend @esterbvila who's a UI/UX expert maybe she can drop in some suggestions here :)

**Comment by esterbvila** [comment]
@FedeClaudi I would suggest to not indent it and maybe try to change words like "Copied", "to" and "Created" to another color, to distinguish them from the urls. It could be another shade of blue, for example.
