### ISSUE TITLE
Output as image

### ISSUE THREAD

**Issue by Wikunia** [FedeClaudi/Term.jl#157]
Hey there,
first of all thanks for the awesome package. 
This might be a weird request or question for this package: is there a way to export the awesomeness that one creates on a terminal to an image?
I'm constantly using this package and make a screenshot for other people outside the terminal world to appreciate it. Would be awesome to have a way to export it somehow automatically. 
Any ideas how to do that?
Thanks in advance.

Cheers,

Ole

**Comment by FedeClaudi** [comment]
Hey, thanks!

Term doesn't currently support that, unfortunately. [rich](https://github.com/Textualize/rich) in python does by converting the output to HTML and from that to SVG, but none of this is implemented in Term yet. 

However, you can redirect your `stdout` to a `.txt` file or something if you want to capture the output. If there's a way to then render the `.txt` as an image you should have all you need, but I don't know of any such methods yet.

**Comment by t-bltg** [comment]
@Wikunia, see also the discussion at https://github.com/FedeClaudi/Term.jl/discussions/121.
