### ISSUE TITLE
how to render only part of tree?

### ISSUE THREAD

**Issue by anandijain** [FedeClaudi/Term.jl#159]
```julia 
julia> tt = Term.Trees.Tree(AbstractFloat)
 Number                      
━━━━━━━━                     
   │                         
   ├── Complex               
   └── Real                  
       ├── Rational          
       ├── AbstractIrrational
       ├── AbstractFloat     
       │   ├── BigFloat      
       │   ├── Float32       
       │   ├── Float64       
       │   └── Float16       
       └── Integer           




julia> tt.nodes[1]


```
I don't really know any of the internals to Term, but I was looking at PkgDependency and I wanted to look at specific subtrees. 

I wanted to make it just work with the AbstractTrees.jl interface, but `AbstractTrees.children(t::Term.Trees.Tree) = t.nodes` doesn't seem like it works as I expected. 

I really like the pretty printing, but it doesn't seem like subtrees are shown the same way 

thanks

**Comment by FedeClaudi** [comment]
I went back to this, working on it: https://github.com/FedeClaudi/Term.jl/pull/187
