### ISSUE TITLE
Is it possible to set a specific alignment for each part of the text within a Term.jl's Panel?

### ISSUE THREAD

**Issue by shayandavoodii** [FedeClaudi/Term.jl#163]
I want to apply a specific alignment for each part of a text within a Panel. Expected output:
```julia
╭────────────────────────────────────────────────╮
│  left                                          │
│                    center                      │
╰────────────────────────────────────────────────╯
```
Then I tried:
```julia
julia> using Term: Panel

julia> println(
           Panel(
               "{bold left}left{/bold /left}\n{center}center{/center}",
               width=50
           )
       )
╭────────────────────────────────────────────────╮
│  {bold left}left{/bold /left}                  │
│  center                                        │
╰────────────────────────────────────────────────╯
```
But it aligns them all to the left.  
I want to know even if this is possible to be done.

P.S: [Cross-post](https://stackoverflow.com/questions/74531234/is-it-possible-to-set-a-specific-alignment-for-each-part-of-the-text-within-a-te)

**Comment by FedeClaudi** [comment]
Hey, 

Given a string, that gets treated as a single piece of text and justified as a block. 
However you can get the result you desire like so:

```julia
using Term



left = RenderableText("this text goes left"; width=60, justify=:left)
right = RenderableText("{green}and this one goes right{/green}"; width=60, justify=:right)

Panel(left, right; fit=true)
```

<img width="344" alt="image" src="https://user-images.githubusercontent.com/17436313/203339298-a6259745-a7eb-4fd4-978c-03b4c4d81068.png">

**Comment by shayandavoodii** [comment]
Hi,
Thanks, Fede.
