### ISSUE TITLE
Error messages not shown in edit mode

### ISSUE THREAD

**Issue by TorkelE** [FedeClaudi/Term.jl#178]
Hello,
I have been trying teh error messages from this package. They are neat, but do not seem to work in `]` mode. Here's a simple example:
![image](https://user-images.githubusercontent.com/18099310/206299144-b593fd72-c9c3-4e5e-afa2-6f95547035e0.png)

**Comment by FedeClaudi** [comment]
Thanks for letting me know. I'll have to see what's causing it.
