### ISSUE TITLE
v2.0 pre-release issues

### ISSUE THREAD

**Issue by FedeClaudi** [FedeClaudi/Term.jl#201]
Noting problems while testing initial release of v2.0

- [x] intermitted error message display
- [x] progress bar with `:detailed` columns too wide.
- [x] logging doesnt show array size and doesn't trim stuff. Tuples have weird shape
- [x] `MethodError: no method matching frame_module(::Tuple)` when rendering errors
- [x] improvements to progress bar styling: https://github.com/FedeClaudi/Term.jl/issues/202  and docstrings
- [x] errors file links not working correctly (see below)

**Comment by VarLad** [comment]
@FedeClaudi Any idea if its possible to change the file link here to the actual (full) filename, instead of relative filename? 
![image](https://user-images.githubusercontent.com/51269425/219727038-228c5c9a-d51d-4437-8fb7-a826afd254d3.png)

**Comment by FedeClaudi** [comment]
thanks for getting in touch. Yeah, I was trying to save some terminal real-estate with these shortened links but it might be better to have the full thing.

**Comment by VarLad** [comment]
@FedeClaudi I meant, you can keep the display name as `./reduce.jl 95`, but clicking on it should point to the full path of reduce.jl
![image](https://user-images.githubusercontent.com/51269425/219729819-cc5d1083-b374-4466-8321-d835de3e9c1a.png)

Kind like this, this is from another CLI program.
I believe `Link` is being used to do this?

**Comment by FedeClaudi** [comment]
oh I see. In theory the stacktrace is using `Link` but it doesn't seem to be working. I'll look into it. It also seems like not all terminals support ANSI link syntax.

**Comment by FedeClaudi** [comment]
All changes listed above have been implemented. https://github.com/FedeClaudi/Term.jl/pull/204 will close this.
