### ISSUE TITLE
Feature request: improved Progressbar styling options - color/line style.

### ISSUE THREAD

**Issue by gitboy16** [FedeClaudi/Term.jl#202]
Hi,
Thank you for the package.
Not an issue, just me struggling to understand how the package works.
Is there a way to set the progressbar color to just one color instead of having it to change color depending on progress?
I noticed that it is set via RBGColor but failed to understand how it works.
Also is there a way to change the shape of the progress line and make it more like ProgressMeter? .i.e. a a fat line...
Thank you

**Comment by FedeClaudi** [comment]
Hello, 

Thanks for your interest in Term!

Currently `ProgressBar` accepts a vector of three RGB colors (see [here](https://github.com/FedeClaudi/Term.jl/blob/fbb21d1942f8a3f3c9e03a245483540b9d6f9384/src/progress.jl#L295)). You can create at `RGBColor` type [from a string](https://github.com/FedeClaudi/Term.jl/blob/fbb21d1942f8a3f3c9e03a245483540b9d6f9384/src/colors.jl#L38). 
If you want to use a single color you can just pass the same color three times. This is a bit awkward so I'll add it so that in the future you will be able to pass a single color, as a string.

Currently there's no option to change the shape of the progress line. The shape is determined by the characters used by [`ProgressColumn`](https://github.com/FedeClaudi/Term.jl/blob/fbb21d1942f8a3f3c9e03a245483540b9d6f9384/src/_progress.jl#L209). I'll add the possibility to pass different charaters!

**Comment by gitboy16** [comment]
Yes I tried this but it did not work. All the below progressbars give me the same color. Is it the same for you?
```julia

using Term.Progress

import Term.Colors: RGBColor

pbar = ProgressBar(;colors = [
        RGBColor("(0.5, 1, 0.5)"),
        RGBColor("(0.5, 1, 0.5)"),
        RGBColor("(0.5, 1, 0.5)"),
    ])
job1 = addjob!(pbar; N=15)
job2 = addjob!(pbar; N=10)

with(pbar) do
    for i in 1:15
        update!(job1)
        update!(job2)
        sleep(0.1)
    end
end

pbar = ProgressBar(;colors = [
        RGBColor("(0.5, 255, 0.5)"),
        RGBColor("(0.5, 255, 0.5)"),
        RGBColor("(0.5, 255, 0.5)"),
    ])
job1 = addjob!(pbar; N=15)
job2 = addjob!(pbar; N=10)

with(pbar) do
    for i in 1:15
        update!(job1)
        update!(job2)
        sleep(0.1)
    end
end

pbar = ProgressBar(;colors = [
        RGBColor("(0.5, 255, 255)"),
        RGBColor("(0.5, 255, 255)"),
        RGBColor("(0.5, 255, 255)"),
    ])
job1 = addjob!(pbar; N=15)
job2 = addjob!(pbar; N=10)

with(pbar) do
    for i in 1:15
        update!(job1)
        update!(job2)
        sleep(0.1)
    end
end

pbar = ProgressBar(;colors = [
        RGBColor("(255, 0,0)"),
        RGBColor("(255, 0,0)"),
        RGBColor("(255, 0,0)"),
    ])
job1 = addjob!(pbar; N=15)
job2 = addjob!(pbar; N=10)

with(pbar) do
    for i in 1:15
        update!(job1)
        update!(job2)
        sleep(0.1)
    end
end
```

**Comment by FedeClaudi** [comment]
mmm for me

```julia
pbar = ProgressBar(;
colors = [
        RGBColor("(0.5, 1, 0.5)"),
        RGBColor("(0.5, 1, 0.5)"),
        RGBColor("(0.5, 1, 0.5)"),
]
)
```

gives a purple line while

```julia
vpbar = ProgressBar(;
colors = [
    RGBColor("(255, 0,0)"),
    RGBColor("(255, 0,0)"),
    RGBColor("(255, 0,0)"),
]
)
```
gives a white one. 
For the others, you can express RGB colors as either integers in the 0-255 range or floats in 0-1 range, but not both at the same time.

**Comment by gitboy16** [comment]
Very strange. By the way I am on windows, could it be the issue?

**Comment by gitboy16** [comment]
I hope the issue isn't that I am color blind 😂

**Comment by gitboy16** [comment]
Ok the issue happens only with microsoft windows terminal... not sure why!
It works fine in vs code and in cmd.

**Comment by FedeClaudi** [comment]
ah yes that may very well be the reason. Windows terminal can't handle as many colors as more modern ones!

**Comment by gitboy16** [comment]
Understood. Thank you. One last thing, do you think it is possible to do something similar to the progress bar of Julia package manager. 
Discussion : https://discourse.julialang.org/t/replicate-pkg-jl-progress-bar/84217
It does not need to be exactly the same.
You actually are almost doing it 
```julia
using Term
using Term.Progress

pbar = Term.ProgressBar()
foreachprogress(1:100, pbar,   description = "Outer    ", parallel=true) do i
    foreachprogress(1:5, pbar, description = "    Inner") do j
        sleep(rand() / 5)
    end
end
```
The only thing missing is the asynchorous or multithreading part

**Comment by gitboy16** [comment]
(Not related but I think you should add your package in the 2023 julia developer survey question 16.)

**Comment by FedeClaudi** [comment]
> (Not related but I think you should add your package in the 2023 julia developer survey question 16.)

I don't know what that is?


Regarding your question, it should be just a matter of adding/removing jobs from the progress bar. Like:

```julia

pbar = ProgressBar()
job1 = addjob!(pbar; description = "Job 1")

with(pbar) do
    for i in 1:50
        i == 15 && (job2 = addjob!(pbar; description = "Job 2"))
        i == 40 && removejob!(pbar, job1)

        update!.(pbar.jobs)
        sleep(0.1)
    end
end
```

and playing around with columns/style to get the look you need. I **think** it should be okay if the code within the `do` statement uses other processes, as long as `update!` is called.

**Comment by gitboy16** [comment]
Thanks I will try your code and let you know.
Check this link for the developer survey:
https://discourse.julialang.org/t/request-for-input-2023-julia-survey/94596

**Comment by FedeClaudi** [comment]
oh cool! I've added it!

**Comment by FedeClaudi** [comment]
I'm working on adding options to make it easier to style progress bars. These will be implemented as part of `v2.0.1` being developed at https://github.com/FedeClaudi/Term.jl/pull/204

**Comment by FedeClaudi** [comment]
With the changes in the PR linked above, one can set the characters to be used by the progress line and you can also just pass a single color as a string to get the color you want. 
Additionally, you can set column kwargs per-job to increase customization. 

```julia

pbar = ProgressBar(; expand = true, columns=:detailed, colors="#ffffff", 
    columns_kwargs = Dict(
        :ProgressColumn => Dict(:completed_char => '█', :remaining_char => '░'),
    )
)
job = addjob!(pbar; N = 100, description="Test")

job2 = addjob!(
    pbar; 
    N = 100, 
    description="Test2", 
    columns_kwargs = Dict(
        :ProgressColumn => Dict(:completed_char => 'x', :remaining_char => '_'),
    )
)

with(pbar) do
    for i in 1:100
        update!(job)
        update!(job2)
        sleep(0.01)
        i == 45 && break
    end
end

```

<img width="533" alt="image" src="https://user-images.githubusercontent.com/17436313/219958101-da381f0d-5b96-415a-ac13-60b387d2a345.png">

**Comment by gitboy16** [comment]
The following does not work for me:
```julia
pbar = ProgressBar()
job1 = addjob!(pbar; description = "Job 1")

with(pbar) do
    for i in 1:100
        i == 15 && (job2 = addjob!(pbar; description = "Job 2"))
        i == 10 && (job3 = addjob!(pbar; description = "Job 3"))
        i == 25 && (job4 = addjob!(pbar; description = "Job 4"))
        i == 40 && removejob!(pbar, job2)
        i == 50 && removejob!(pbar, job3)
        i == 60 && removejob!(pbar, job4)
        update!.(pbar.jobs)
        sleep(0.1)
    end
end
```
It seems that job2 needs to be defined beforehand. Also does this runs jobs asynchronously?

**Comment by FedeClaudi** [comment]
Hey,

The need to define `job2` is a Julia thing, not Term. You can see it with this example:
```julia

for i in 1:100
    i == 20 && (x = 1)
    i == 50 && (y = 2x) # this will error: UndefVarError: x not defined    
end
```

In the example you've shared you need to define `job2, job3, job4` within the `do` statement above the loop for them to be used correctly. You can just do: `job2, job3 = nothing, nothing` and that'll work. It's a bit ugly, I also excepected your code to work, but nothing I can do I'm afraid. 

Of course you could do something else, like using `filter!` or something like that to get the job you need from `pbar.jobs` without storing each job explicitly in a variable. 

Regarding the asynchronous question. `with(pbar)` executes the expression in your `do` statement in a separte thread from the one that creates and updates the progress bar display. At each "frame" the progress bar just draws all the jobs it currently has. If your code is spawning other threads adding/removing jobs that **should be fine**. I haven't tried it, to be honest, but I would be interested to see an example. 


There's also `foreachprogress` which handles nested loops pretty well and assigns different threads to each. 

Finally, Term's progress bar functionality should be compatible with `ProgressLogging` too, which I think supports async stuff.

**Comment by gitboy16** [comment]
Thank you
I tried to play a little bit with:
```julia
using Term.Progress
import Term.Progress: SPINNERS

pbar = ProgressBar(;colors="#11CF62", columns=:default)
job = addjob!(pbar; N=100, description = "Progress...")
start!(pbar)

columns_kwargs = Dict(:SpinnerColumn => Dict(:spinnertype => :circle, :style => "white"),:CompletedColumn => Dict(:style => "dim"))

with(pbar) do
    job1, job2, job3, job4 = nothing, nothing, nothing, nothing
    for i in 1:100
        
        i == 5  && (job1 = addjob!(pbar; description = "Job 1", columns_kwargs = columns_kwargs))
        i == 15 && (job2 = addjob!(pbar; description = "Job 2", columns_kwargs = columns_kwargs))
        i == 10 && (job3 = addjob!(pbar; description = "Job 3", columns_kwargs = columns_kwargs))
        i == 25 && (job4 = addjob!(pbar; description = "Job 4", columns_kwargs = columns_kwargs))
        
        i == 70 && removejob!(pbar, job1)
        i == 40 && removejob!(pbar, job2)
        i == 50 && removejob!(pbar, job3)
        i == 60 && removejob!(pbar, job4)
        
        update!.(pbar.jobs)
        sleep(0.1)
    end
end

stop!(pbar)
```
Need to start julia like that `julia -t 4`

```julia
using Term
using Term.Progress

pbar = Term.ProgressBar(;colors="#11CF62")

foreachprogress(1:100, pbar,   description = "Progress...", parallel=true) do i
    foreachprogress(1:5, pbar, description = "Task $i [thread $(Threads.threadid())] ...") do j
        sleep(rand() / 5)
    end
end
```
I think the second code is closer to what I am looking for although I noticed some issues:
- the bar inside the maun loop can't be of a different shape than the one from the outer loop. Can that be a feature request?
- it seems that the printing add additional empty lines (scrolling down) and I also get the main progress bar is printed twice. Is that a bug?
 Thanks!

**Comment by FedeClaudi** [comment]
that seems indeed to be true, I'll have to investigate.
