### ISSUE TITLE
Broken underline

### ISSUE THREAD

**Issue by VarLad** [FedeClaudi/Term.jl#211]
The update to 2.0.2 now has long underline under REPL and ./reduce.jl in the following image:
![image](https://user-images.githubusercontent.com/51269425/226172336-ad393459-e4af-43bf-98d9-2bc3f6084118.png)

**Comment by VarLad** [comment]
Not sure if its intentional or not

**Comment by FedeClaudi** [comment]
Nope, not intentional. Will be fixed by: https://github.com/FedeClaudi/Term.jl/pull/212
