### ISSUE TITLE
Don't write inside of the package directory

### ISSUE THREAD

**Issue by maleadt** [FedeClaudi/Term.jl#237]
During testing of this package, output is being written to a directory inside of the package: https://github.com/FedeClaudi/Term.jl/blob/094339bc1a41a73296cec54c2a36dc3c52457076/test/10_test_inspect.jl#L16-L21

This is not OK, as packages can be installed in a read-only environment. As a result, this package fails testing on PkgEval.
For the time being, I'll blacklist testing of this package, but if this gets fixed feel free to ping me or open a PR on PkgEval.jl to resume testing.

**Comment by FedeClaudi** [comment]
Thanks
