### ISSUE TITLE
`[]` should be `{}` in "Where did my brackets go" section

### ISSUE THREAD

**Issue by jerlich** [FedeClaudi/Term.jl#243]
Cool package. When reading the docs, I noticed a `[]` that should have been updated to a `{}`

https://github.com/FedeClaudi/Term.jl/blob/094339bc1a41a73296cec54c2a36dc3c52457076/docs/src/basics/styled_text.md?plain=1#L89C211-L89C216

**Comment by FedeClaudi** [comment]
Thanks - has been fixed
