### ISSUE TITLE
Progress bar for downloads / API calls 

### ISSUE THREAD

**Issue by danielw2904** [FedeClaudi/Term.jl#39]
As per our [twitter talk](https://twitter.com/Federico_claudi/status/1504123579901829124?s=20&t=LpPIAUIRh_BZBOCU9_O6TA) it would be nice to have columns for downloads (speed, size) and API calls (Maybe show current call, share of calls completed). Let me know if I can help.

**Comment by FedeClaudi** [comment]
Closed it by accident sorry. 

It's in the pipeline.

**Comment by FedeClaudi** [comment]
Working on it, will come with: https://github.com/FedeClaudi/Term.jl/pull/62

**Comment by FedeClaudi** [comment]
The next release will include a `DownloadedColumn` which can be used like this:


```Julia
using Term.progress
using Term
import Term.progress: SeparatorColumn, ProgressColumn, DescriptionColumn, DownloadedColumn


FILESIZE = 2342341
CHUNK = 2048
nsteps = Int64(ceil(FILESIZE / CHUNK))
@info nsteps

mycols = [DescriptionColumn, SeparatorColumn, ProgressColumn, DownloadedColumn]

pbar = ProgressBar(; columns=mycols,  width=140)
job = addjob!(pbar; N=FILESIZE)

with(pbar) do 
    for i in 1:nsteps
        update!(job; i=CHUNK)
        sleep(0.001)
    end
end
```

The docs show how to use the new progress bar API: https://fedeclaudi.github.io/Term.jl/dev/adv/progressbars/

I can ping when the new release comes out in a few days, if you'd like to test this out.

**Comment by FedeClaudi** [comment]
Please install the code under development with
```
] add https://github.com/FedeClaudi/Term.jl
```
to test.
