### ISSUE TITLE
Word wrap text

### ISSUE THREAD

**Issue by jeremiahpslewis** [FedeClaudi/Term.jl#42]
In the Readme, it looks like the text is being wrapped on a character, not a word level, which makes things a bit hard to read

**Comment by FedeClaudi** [comment]
Hi, 

Thanks for reporting this. The README is a bit outdated, its fixed now:
https://fedeclaudi.github.io/Term.jl/dev/

<img width="519" alt="image" src="https://user-images.githubusercontent.com/17436313/158814096-66cd2893-7e1a-457f-9671-c873e0318416.png">

**Comment by FedeClaudi** [comment]
Re-opened this as the text justification could be improved (see second line in top-right of image)
