### ISSUE TITLE
Interrupting progress bar breaks future printing

### ISSUE THREAD

**Issue by kescobo** [FedeClaudi/Term.jl#55]
This is pretty consistently breaking printing on my system:

```
julia> import Term.progress: track, ProgressBar, update, start, stop

julia> loop = collect(1:10);

julia> for i in track(loop)
           sleep(0.5)
       end
Running... ● ━━━━━━━━━━━━━━━━━━                                            ●  3/10  30 %
^CERROR: InterruptException:
# ... < truncated >

julia> for i in track(loop)
           sleep(0.5)
       end

julia> import Term: install_term_logger

julia> @info "working"
[ Info: working

julia> install_term_logger();

julia> @info "not :-("

julia>
```

**Comment by kescobo** [comment]
It seems that even `println()` stops working after this, though the default logging seems unaffected.

**Comment by FedeClaudi** [comment]
As noted in the [docs](https://fedeclaudi.github.io/Term.jl/dev/adv/progressbars/#A-note-on-STDOUT), progress bar temporarily re-directs `stdout`. If the `ProgressBar` is not correctly stopped it will not restore `stdout` correctly. 

I think there should be a clearer warning in the docs about this since it might not be clear from the current text. Also perhaps this shouldn't be the default behavior.

**Comment by kescobo** [comment]
Yeah, this behavior seems undesirable. I wonder if there's a way to fail more gracefully, or at minimum have a way to wrench back normal behavior.

**Comment by FedeClaudi** [comment]
Yeah, that's true.  In Python the solution would be to have a context manager for the progress bar.  Perhaps the solution is to encapsulate the progress bar in a `do` block 🤔

**Comment by TheCedarPrince** [comment]
I agree with @kescobo here as this is quite a bummer for me.
Introduces a bit of brittleness into the REPL such that I worry that if my code is not fully correct, it'll break printing and I have to restart my REPL session - which for me can be a rather large productivity hit.
So were you thinking about syntax like this @FedeClaudi ?

```julia
import Term.progress: track

myvec = collect(1:5)

ProgressBar(; N = length(myvec)) do pbar
     for i in myvec
        println(i)
        update(pbar)
     end
end
```

This wouldn't be so bad I don't think as you still create a ProgressBar object that is referenced to `pbar` such that you can then arrange it in a given panel.
Although perhaps you had something else in mind!
I hope this issue gets addressed soon - happy to assist in testing where I can. 😄

**Comment by FedeClaudi** [comment]
Hello, 

Please note that this:
```Julia
import Term.progress: ProgressBar, update


pbar = ProgressBar(; N=100, redirectstdout=false)

for i in 1:100
    update(pbar)
    i % 25 == 0 && break
end
print("out")
```
and this
```Julia
import Term.progress: ProgressBar, update, stop


pbar = ProgressBar(; N=100)

for i in 1:100
    update(pbar)
    i % 25 == 0 && break
end
stop(pbar)
print("out")
```

work. Of course in the second case you can't make sure that `stop(pbar)` is reached in case of an error while in the loop.
So you can use the progressbar confidently before a new version comes out.

I'm currently stuck finding a clever way to [reshape text](https://github.com/FedeClaudi/Term.jl/issues/57), but I'm close to finishing that. After that a new version of Term will come out which just features 'under the hood' improvements with performance. I'm hoping by the end of the weekend to have it out.

After that I will start working on the progress bar functionality and this will be one of my first concerns.

**Comment by FedeClaudi** [comment]
When https://github.com/FedeClaudi/Term.jl/pull/62 is merged stdout will not be re-directed by default, although it will remain as an option. I'd still like to find a way to have it as default but being able to fail gracefully.
