### ISSUE TITLE
Failed to reshape text

### ISSUE THREAD

**Issue by YongHee-Kim** [FedeClaudi/Term.jl#57]
I've encountered strange error 

``` julia 
using Term

julia> a = """┌────────────────┬────────────────┬────────────────┬────────────────┬──────────────"""
julia>Panel(a)

ERROR: "Failed to reshape text: StringIndexError(\"┌────────────────┬────────────────┬────────────────┬────────────────┬──────────────\", 83) - target width: 82"
Stacktrace:
 [1] reshape_text(text::SubString{String}, width::Int64)
   @ Term C:\Users\Maste\.julia\packages\Term\tVGFF\src\__text_utils.jl:340
 [2] (::Term.renderables.var"#7#9")(ln::SubString{String})
   @ Term.renderables C:\Users\Maste\.julia\packages\Term\tVGFF\src\renderables.jl:97
......
```

But removing just one more letter works 
``` julia 
using Term

julia> a = """┌────────────────┬────────────────┬────────────────┬────────────────┬─────────────""" 
julia>Panel(a)
Panel <: AbstractRenderable size: Measure (w: 88, h: 3)
```

**Comment by FedeClaudi** [comment]
Thanks for reporting this. I'm currently re-writing the text reshaping functionality to make it faster and more robust, I'll add this as a test case to ensure that everything works as expected.

**Comment by FedeClaudi** [comment]
As you can see from this commit history. this gave me quite a few headaches:
<img width="356" alt="image" src="https://user-images.githubusercontent.com/17436313/160236954-1da88eb4-864e-45d7-a69f-02e6807984ef.png">

but, I've finally got text reshaping to be both fast and resilient to multiple complex use cases. It can now handle strings like the one above with characters with width > 1 and with multi-codeunits chars too. It's not perfect in that the style of the reshaped text doesn't always match perfectly with that of the original text, but that's as good as I can get it for now:

```Julia
import Term: reshape_text
import Term.consoles: clear


strings = [
    # latin alphabet
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "Lorem [red]ipsum dolor sit [underline]amet, consectetur[/underline] adipiscing elit, [/red][blue]sed do eiusmod tempor incididunt[/blue] ut labore et dolore magna aliqua.",
    "Lorem[red]ipsumdolorsit[underline]amet, consectetur[/underline] adipiscing elit, [/red]seddoeiusmo[blue]dtemporincididunt[/blue]ut labore et dolore magna aliqua.",

    # arab
    "استنكار  النشوة وتمجيد الألم نشأت بالفعل، وسأعرض لك",
    "لكن لا بد أن أوضح لك أن كل ه[/green]ذه الأفكار[green] المغلوطة حو[/red]ل استنكار  النشوة وتمجيد الألم نشأت بالفعل، وسأعرض لك التفاصيل لتكتشف حقيقة و[red]أساس تلك السعادة",

    # thai
    "ต้าอ่วยวาทกรรมอาว์เซี้ยว กระดี๊กระด๊า ช็อปซาดิสต์โมจิดีพาร์ตเมนต์ อินดอร์วิว สี่แยกมาร์กจ๊อกกี้ โซนี่บัตเตอร์ฮันนีมูน ยาวีแพลนหงวนสคริปต์ แจ็กพ็อตต่อรองโทรโข่งยากูซ่ารุมบ้า บอมบ์เบอร์รีวีเจดีพาร์ทเมนท์ บอยคอตต์เฟอร์รี่บึมมาราธอน ",
    "ต้าอ่วยวาท[red]กรรมอาว์เซี้ยว กระดี๊กระด๊า [/red]ช็อปซาดิสต์โมจิดีพาร์ตเม[blue underline]นต์ อินดอร์วิว สี่แยกมาร์กจ๊อกกี้ โซนี่บัตเต[/blue underline]อร์ฮันนีมูน ยาวีแพลนหงวนสคริปต์ แจ็กพ็อตต่อรองโทรโข่งยากูซ่ารุมบ้า บอมบ์เบอร์รีวีเจดีพาร์ทเมนท์ บอยคอตต์เฟอร์รี่บึมมาราธอน ",

    # korean
    "국가유공자·상이군경 및 전몰군경의 유가족은 법률이 정하는 바에 의하여",
    "국[red]가유공자·상이군[bold]경 및 전[/bold]몰군경의 유[/red]가족은 법률이 정하는 바에 의하여",

    # large chars
    "┌────────────────┬────────────────┬────────────────┬────────────────┬──────────────",
    "┌────────────abcde────┬──────────── ────┬────────abcde fghi────────┬────────────────┬──────────────",
    "┌─────────[red]───ab[/red]cde────┬──────[green]────── ────┬────────abcde fghi[/green]────────┬────────────────┬──────────────",
    "┌──────────[red]────[/red]──┬[blue bold]────────────────┬──[/blue bold]──────────────┬────────────────┬──────────────end",

    # nospaces
    "."^100  ,
    ".[red]|||[/red]...."^10,
    ".|||...."^10,
]

clear()
width = 21
for text in strings
    println('_'^width)
    println(reshape_text(text, width))
    @time reshape_text(text, width)
end
```

gives:
<img width="312" alt="image" src="https://user-images.githubusercontent.com/17436313/160237029-3ff250dd-c04b-4c10-98d5-4a6c7ba8784e.png">
<img width="311" alt="image" src="https://user-images.githubusercontent.com/17436313/160237039-2f5a4c9d-61dc-4fed-8a78-1c762daf4245.png">
<img width="325" alt="image" src="https://user-images.githubusercontent.com/17436313/160237041-b425387e-55e2-414f-93ac-25813f5067b6.png">


Given how central text-reshaping is to Term's functionality it was important to improve this, but boy was it hard! Thanks for reporting this issue, it will not throw errors in the next iteration of Term.

**Comment by YongHee-Kim** [comment]
You did wonderful job! I'm thrilled for the upcoming update😄 

Since text warp is very useful for many applications, maybe text warp code could be more useful to the ecosystem by making it independent package in the future. There is [TextWrap.jl](https://juliahub.com/ui/Packages/TextWrap/hiFMy/1.0.1) but It doesn't seem to support formatting nor unicode like yours do.

**Comment by FedeClaudi** [comment]
>You did wonderful job! I'm thrilled for the upcoming update😄

It's not perfect yet. For texts with both style and multiple-widths characters the style is not faithfully carried over to the reshaped text yet. But the text itself should be correct and it won't throw errors at least. 

> Since text warp is very useful for many applications, maybe text warp code could be more useful to the ecosystem by making it independent package in the future. There is [TextWrap.jl](https://juliahub.com/ui/Packages/TextWrap/hiFMy/1.0.1) but It doesn't seem to support formatting nor unicode like yours do.

That's an interesting idea. The code I'm using now has extra complexity due to the fact that it needs to deal with style information too. But perhaps there's a way to have isolate the "reshaping" part and have that as a separate package. Do you really think there would be a use for that?

**Comment by YongHee-Kim** [comment]
Yeah, I am quite sure text warp will have use for its own for various reasons. But of course, making the interface convenient enough for others to use and discoverable is whole different issue we cannot know at this point. But breaking down bigger modules to smaller parts has more advantages than disadvantages. So, I think it is worth a shot. 

I want to try to make a text warp into a separate package after your next update. (If you are ok with it)

**Comment by FedeClaudi** [comment]
I see.

I don't think I want to take this on, but I'm more than happy for you or anyone else to take the code and adapt it for a standalone package. 

The code is here: https://github.com/FedeClaudi/Term.jl/blob/da74af71fc934953c912f1840f8da504b5383157/src/__text_utils.jl#L454

Lines 464 and 521 have bits that are important to preserve ANSI style information that perhaps you'd want to exclude.

**Comment by FedeClaudi** [comment]
Following your advice, it will come out here: https://github.com/FedeClaudi/TextBox.jl
