### ISSUE TITLE
escape style brackets

### ISSUE THREAD

**Issue by filchristou** [FedeClaudi/Term.jl#59]
Is there a way to escape style brackets ?
e.g.
```julia
tprint("an array [1,2,3] is the input")
```
prints
![image](https://user-images.githubusercontent.com/27723218/160173268-ee2b23df-17a2-42bf-b16e-3e9d998b5204.png)

I found in the documentation the `Term.escape_brackets`:
```julia
tprint(Term.escape_brackets("an array [1,2,3] is the input"))
```
![image](https://user-images.githubusercontent.com/27723218/160173387-b203b596-66a7-4436-9cea-8cc8c04338ab.png)

but it's not quite the same.
is there a way to print single brackets in a `Renderable` ?

**Comment by FedeClaudi** [comment]
Hi, 

Not currently, but in the next version which will come out soon (a few days to a couple of weeks) the markup regex business [will work a bit differently](https://github.com/FedeClaudi/Term.jl/blob/eb5d7b110cb84d6a2eba03c53963850903830fee/src/__text_utils.jl#L22) internally. This means that double square brackets will be ignored and you can avoid using `escape_brackets` and simply write your text as `"this is my array [[1, 2, 3]]"`.

Then, the text within the double brackets will be ignored during styling and just before printing [this function](https://github.com/FedeClaudi/Term.jl/blob/eb5d7b110cb84d6a2eba03c53963850903830fee/src/__text_utils.jl#L145) will be used to replace the double brackets with single ones. So the final output should look like what you'd want it to be and the style will be applied correctly too. 

I'll update here once the new version is released

**Comment by filchristou** [comment]
thanks for the quick reply, your description on the internals and ofc also for the package!

**Comment by FedeClaudi** [comment]
The next version of `Term` will ignore "escaped" (double) brackets: 
<img width="469" alt="image" src="https://user-images.githubusercontent.com/17436313/160253533-81a9d2a2-9f82-47c0-a22f-f546f865ff22.png">

Anything that is between `[[...]]` will be treated differently from a style tag `[...]` or `[/...]`. You can either escape your brackets manually or use `escape_brackets`
<img width="336" alt="image" src="https://user-images.githubusercontent.com/17436313/160253578-1f881155-93ed-4237-9ce9-f0929168e29c.png">
