### ISSUE TITLE
[Feature request] allow AbstractDict in Tree

### ISSUE THREAD

**Issue by Wikunia** [FedeClaudi/Term.jl#68]
It seems like the `Tree` functionality doesn't work with `OrderedDict`.
Maybe a simple change from using `Dict` to `AbstractDict` already solves this.
I would like to have a specified order of the tree display which can only be done with `OrderedDict`

**Comment by FedeClaudi** [comment]
Done, this

```Julia

a = OrderedDict(
    "z"=>[1, 2, 3],
    "x"=> 123,
)

print(Tree(a))
```

now works and it has the desired effect, very good idea! It will come out with the next release.

**Comment by Wikunia** [comment]
Awesome thanks
