### ISSUE TITLE
Tree hide limits

### ISSUE THREAD

**Issue by filchristou** [FedeClaudi/Term.jl#69]
Hi. Is there a way to configure the limits of hiding output because it's too long ?
e.g. in the following expression
```julia
 print(Tree(Dict("A very very very long tile" => "And a very very very very very very very long value")))
```
![image](https://user-images.githubusercontent.com/27723218/161331245-b0e199a6-fb52-4f2b-9cc7-d7913b5f190a.png)

ideally I would like to not hide any information and show everything even if it has to break in the next line.

Thanks in advance :)

**Comment by FedeClaudi** [comment]
Thanks for suggesting this. I can definitively  add that in, but I need to think about what the best way is. Instead of having it just as an option for `Tree` perhaps it can be general setting, perhaps through an IOContext.

**Comment by FedeClaudi** [comment]
From the next release you can do:

```Julia
import Term: theme
theme.tree_max_width = 100
```

To set the max allowed length of tree elements' string (until I find a cleverer way to do this)

**Comment by filchristou** [comment]
is there a slick way to set it to unlimited rather than putting something like `typemax(Int)` ?

**Comment by FedeClaudi** [comment]
I can add it in I think, but can I ask why? In what scenario would you like to have extremely long labels on the tree (just trying to understand).

**Comment by filchristou** [comment]
Nothing crazy.
I have a recursive structure of elements.
Each element can vary in representation size and can end up being quite big, so I would probably end up using a really big value as a tree width to have my mind at ease.
I wanted to use it to inspect the structure without losing any information. 

> To set the max allowed length of tree elements' string 

wait a minute. Does this count the number of characters or the width of the elements ?
For example if I have an element of 150 characters which I break down to 3 lines of 50, will it trigger the threshold or not ?

**Comment by FedeClaudi** [comment]
I've changed it so that setting the limit to `-1` means that you can have texts of any length. 

>  For example if I have an element of 150 characters which I break down to 3 lines of 50, will it trigger the threshold or not ?

No it's width, for a multi-line text its the width of the largest line. This also takes into account unicode characters with width >1 and ncodeunits > 1 and it ignores styling information (markup and ANSI alike). Though to be honest multi-line tags would break the layout I expect.

**Comment by FedeClaudi** [comment]
Please install the code under development with
```
] add https://github.com/FedeClaudi/Term.jl
```
to test.
