### ISSUE TITLE
"UndefVarError: r not defined" when using progress bars on not-precompiled code

### ISSUE THREAD

**Issue by ultrapoci** [FedeClaudi/Term.jl#77]
I have this function:
```julia
import Term.progress: track

pbar(x) = track(x; 
	description = "Termalization",
	expand = true,
	update_every = 1,
	columns = :detailed
)

function testbar(params::Dict)
	@unpack β, nterm, nover, norm_every, dims, start = params
	lattice = Lattice(dims, start = start)

	for n in pbar(1:10)
		lattice_overrelaxation!(lattice, nover)
		lattice_heatbath!(lattice, β)
		if n % norm_every == 0
			lattice_normalization!(lattice)
		end
	end
	lattice
end
```

If I run this, the progress bar appears, it gets stuck for a while, and then this error shows up:
```julia
ERROR: UndefVarError: r not defined
Stacktrace:
  [1] update(::Term.progress.ETAColumn, ::Int64, ::Int64, ::String, ::Dates.DateTime)
    @ Term.progress E:\Programmi\Julia\.julia\packages\Term\tVGFF\src\progress.jl:196
  [2] (::Term.progress.var"#12#13"{Term.progress.ProgressBar, String})(c::Term.progress.ETAColumn)
    @ Term.progress E:\Programmi\Julia\.julia\packages\Term\tVGFF\src\progress.jl:442
  [3] iterate
    @ .\generator.jl:47 [inlined]
  [4] collect_to!(dest::Vector{String}, itr::Base.Generator{Vector{Term.progress.AbstractColumn}, Term.progress.var"#12#13"{Term.progress.ProgressBar, String}}, offs::Int64, st::Int64)
    @ Base .\array.jl:782
  [5] collect_to_with_first!(dest::Vector{String}, v1::String, itr::Base.Generator{Vector{Term.progress.AbstractColumn}, Term.progress.var"#12#13"{Term.progress.ProgressBar, String}}, st::Int64)
    @ Base .\array.jl:760
  [6] _collect(c::Vector{Term.progress.AbstractColumn}, itr::Base.Generator{Vector{Term.progress.AbstractColumn}, Term.progress.var"#12#13"{Term.progress.ProgressBar, String}}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{1})
    @ Base .\array.jl:754
  [7] collect_similar
    @ .\array.jl:653 [inlined]
  [8] map
    @ .\abstractarray.jl:2849 [inlined]
  [9] update(pbar::Term.progress.ProgressBar)
    @ Term.progress E:\Programmi\Julia\.julia\packages\Term\tVGFF\src\progress.jl:442
 [10] iterate(e::Term.progress.Track, state::Int64)
    @ Term.progress E:\Programmi\Julia\.julia\packages\Term\tVGFF\src\progress.jl:517
 [11] testbar(params::Dict{Symbol, Any})
    @ Main e:\Università\2020-2021\Tesi\scripts\test.jl:27
 [12] top-level scope
    @ e:\Università\2020-2021\Tesi\scripts\test.jl:35
```

If I remove my functions from the loop and use dummy stuff, like `sleep(0.5)`, it works. But, if I run the same exact loop without `pbar`, the loop runs to completion, and if I redo it, this time using `pbar`, it works, with the progress bar showing correctly. I believe the problem lies in the compilation step, but I don't know how to solve it. I'm using these functions from a local file, which simply gets `include`d, so I don't think I can precompile it (and even then, I've never precompiled stuff so I wouldn't know what I'm doing). 

I'm using Julia 1.7.2, Term 0.2.0 on Windows, using the Visual Studio Code integrated terminal.

**Comment by FedeClaudi** [comment]
Hi, 

sorry I thought I had replied already. I've completely changed the progress bar API for the next release of Term (which will come out in a couple days). I'll ping you for the testing when the release comes out if you'd like to see if the problem persists.

**Comment by ultrapoci** [comment]
Sure, I'm happy to help.

**Comment by FedeClaudi** [comment]
Please install the code under development with
```
] add https://github.com/FedeClaudi/Term.jl
```
to test.

Here's the docs for the new progress bar API: https://fedeclaudi.github.io/Term.jl/dev/adv/progressbars/

**Comment by ultrapoci** [comment]
I've tried the new API but unfortunately I'm having issues. If I use `start!`, `update!`, `stop!` with a newly created `ProgressBar`, no bar is shown. If I use the simpler `@track` macro, the blue header with "progress" written on it is shown, but then nothing. The progress bar appears only at the end of the loop, at 100% completion. 

Again, if I use simple loops with `sleep`, it works fine, with both methods (even though using `@track` prints the "progress" header twice). The issues arise when combining the progress bar with more complex for loops that use custom functions. Do note that these for loops work as intended when using `ProgressMeter.jl`.

**Comment by FedeClaudi** [comment]
Can you provide a minimal working example please?

**Comment by ultrapoci** [comment]
I'm finding hard to come up with a MWE. Here is the repo I'm working on: https://github.com/ultrapoci/Tesi. In the `scripts` folder there's a `test_term.jl` file with an example of `@track` not working compared to `ProgressMeter.jl`. This should let you check with a set of functions that take some computational time and that come from a local package or included file, which may o may not be a problem. Note that the functions I call inside the for loop don't do any kind of output.

**Comment by FedeClaudi** [comment]
I'll investigate. Can I also ask some more details: OS, Julia version, what kind of terminal/where are you running this in?

**Comment by ultrapoci** [comment]
I'm using Windows and Julia 1.7.2. I'm running the code from Visual Studio Code into its integrated terminal.

**Comment by FedeClaudi** [comment]
Mmm okay I'm struggling to replicate this, the following code:

```Julia
using Term.progress

very_slow_fn() = sleep(10)
slow_fn() = sleep(1)

@track for i in 1:100
    i == 1 && very_slow_fn()
    slow_fn()
end
```

works on both mac and windows for me, the progress bar shows up and is updated correctly. Can you try this on your setup?

**Comment by ultrapoci** [comment]
That piece of code works fine. It prints twice the blue header, but other than that the progress bar shows up as intended. It also works when wrapped inside another function which gets called in Main. 

I've tried using the REPL detached from VScode, but it results in the same behaviour: my code doesn't make the bar appear until the very end, while your code works.

**Comment by FedeClaudi** [comment]
Mmm that's weird, I can't tell from your code why it would behave any differently from the example. Is it a specific function that causes the problem (if you comment them out one at the time)

**Comment by ultrapoci** [comment]
Commenting either `lattice_heatbath!` or `lattice_overrelaxation!` doesn't change the outcome. `lattice_normalization!` is too quick to be left alone. I've noticed that if I add `sleep` to the loop it works, even if all the other problematic functions are running. And the amount of seconds doesn't matter: I've tried with `sleep(0.00001)` and the bar works.

**Comment by FedeClaudi** [comment]
that's so weird... I can't replicate it on my side!

**Comment by ultrapoci** [comment]
I've drastically changed the algorithm of my project (tho the main loop is very similar) and for some reason now the progress bar work. I've tested this using `@track` and using `with(pbar)`. Using `@track` still prints the blue header twice, but the progress bar is perfectly functional. My old algorithm still has issues. This is so weird. It must be something on my part, but I can't tell what it is, since I output nothing.

**Comment by FedeClaudi** [comment]
I see, very weird. 

I think that `@track` only does that on windows, but I'll need to investigate. Thanks for testing this out!

**Comment by FedeClaudi** [comment]
I think I'm seeing something similar now that I've started using the new progress bar functionality in my work code: the progress bar either takes a while to show up or it updates every once in a while
It seems that a `sleep` statement at each loop iteration fixes that, but I'm not sure what's going on since the bar rendering [is done in a separate task](https://github.com/FedeClaudi/Term.jl/blob/58e3a0ae2ee0caefc6d208983dcbebae914bb31d/src/progress.jl#L379).  

It also doesn't happen in any of my test code here on Term, so I'm not sure what's going on...

If you still have your code at hand, can you try adding a `sleep` call in your loop?

**Comment by ultrapoci** [comment]
I've updated [my script to test Term](https://github.com/ultrapoci/Tesi/blob/main/scripts/test_term.jl). I test both algorithms, with and without `sleep` in the main loop, using `@track` to use Term's progress bar. 
The old algorithm only works as intended when using `sleep`, while the new algorithm works in both cases. I'm not sure what the key difference might be.

**Comment by FedeClaudi** [comment]
thanks for the update. This is the weirdest thing. My intuition at the moment is that it has do with multiple process and the async updating of the progress bar. Is there a difference in the number of precesses or async operations between the two versions of your code?

**Comment by ultrapoci** [comment]
The new algorithm is distributed and uses multiple processes and `@spawnat` calls, while the old algorithm is not distributed nor multi-threaded. What's weird is that it is the old algorithm, the non-parallel one, that has issues.

**Comment by FedeClaudi** [comment]
that's weird indeed.

I have no clue what's going on, but at least `sleep` although ugly is a painless temporary fix. I won't have time to investigate this weird behavior for the next few weeks, but thank you so much for taking the time to test it out, it will be helpful when I get to it.

**Comment by FedeClaudi** [comment]
The `sleep` issue was fixed thanks to the brilliant folks at [Julia discourse](https://discourse.julialang.org/t/printing-in-a-background-process/81453). Will come out with the next version `v0.4`.
