### ISSUE TITLE
provide methods for `IO` other than `stdout`

### ISSUE THREAD

**Issue by ExpandingMan** [FedeClaudi/Term.jl#78]
As far as I can tell, Term.jl renderables can only be shown properly with the 1-argument `print` methods or with the 1-argument `tprint` methods.

It would be nice to be able to print the expected output to any `IO`.  The main reason I'd like to be able to do this is that it makes it more natural to overload `Base.show(::IO, ::MIME"text/plain", ::T)`, as without this, the only way of writing an appropriate `show` method using Term.jl is with `redirect_stdout`.

**Comment by FedeClaudi** [comment]
This will happen with the next release: https://github.com/FedeClaudi/Term.jl/blob/524e2078292e3f078aa160b6c90d669b91bdffd5/src/tprint.jl#L22

> It would be nice to be able to print the expected output to any IO. The main reason I'd like to be able to do this is that it makes it more natural to overload Base.show(::IO, ::MIME"text/plain", ::T), as without this, the only way of writing an appropriate show method using Term.jl is with redirect_stdout.

Do you have a concrete example of this? So that I can test this functionality before the next release

**Comment by ExpandingMan** [comment]
I've been doing stuff like this
```julia
function termrender(obj::Object)
    Panel(obj.stuff, title=obj.name)
end
Base.show(io::IO, ::MIME"text/plain", obj::Object) = redirect_stdout(() -> termrender(obj), io)
```
The `redirect_stdout` is what I was hoping to eliminate.

**Comment by ExpandingMan** [comment]
Come to think of it, I probably should do
```julia
function Base.show(io::IO, ::MIME"text/plain", obj::Object)
    if get(io, :color, false)
        redirect_stdout(() -> print(termrender(obj)), io)
    else
        show(io, obj)
    end
end
```
As checking if the IO stream supports color seems like a good minimal sanity check for whether it makes sense to try to use Term.jl on it, so you might want to consider doing this in a method you add.

**Comment by FedeClaudi** [comment]
With the next release, the general methods

```Julia
tprint(x) = tprint(stdout, x)
tprint(io::IO, x) = tprint(io, x)
tprint(io::IO, ::MIME"text/html", x) = tprint(io, x)
```

should allow for the behavior that you have in mind. 

> As checking if the IO stream supports color seems like a good minimal sanity check for whether it makes sense to try to use Term.jl on it, so you might want to consider doing this in a method you add.

Term does more than just color though, it can be used for layouts, panels etc even when there's no color information.

**Comment by ExpandingMan** [comment]
> Term does more than just color though, it can be used for layouts, panels etc even when there's no color information.

Oh yeah, it's not perfect by any means, but at least it's *something*.  I'm not aware of any way of testing everything that'd be general and robust enough (you'd still want to have the ability to write to buffers and stuff like that so trying to determine if something is a real TTY seems a bit much).

**Comment by FedeClaudi** [comment]
aye, though it would be good to add more checks for IO contexts and the likes, in the future I guess (unless someone whats to help in 😄 )

**Comment by FedeClaudi** [comment]
Please install the code under development with
```
] add https://github.com/FedeClaudi/Term.jl
```
to test.

**Comment by ExpandingMan** [comment]
Seems to work great (for both `tprint` and `print`), thanks!

**Comment by FedeClaudi** [comment]
awesome, enjoy!
