### ISSUE TITLE
A corner case when rendering Panel with italic title

### ISSUE THREAD

**Issue by findmyway** [FedeClaudi/Term.jl#80]
I'm testing with the latest v3.0

```julia
julia> tprint(Panel(title="12345678: [italic]abcdefg[/italic]", width=20))
╭──── 12345678:... ╮
╰──────────────────╯

julia> tprint(Panel(title="12345678: [italic]abcdefg[/italic]", width=24))
╭──── 12345678: ╮
╰──────────────────────╯

julia> tprint(Panel(title="12345678: [italic]abcdefg[/italic]", width=28))
╭──── 12345678: abcdefg ───╮
╰──────────────────────────╯
```

<img width="548" alt="image" src="https://user-images.githubusercontent.com/5612003/164981349-b25fd32f-df8e-42d0-af7a-540f33c3e626.png">

**Comment by FedeClaudi** [comment]
Thank's, 1 and 3 are expected behaviors but 2 gets thrown off by the style information. 

This seems to work:

```Julia
tprint(Panel(title="12345678: abcdefg",title_style="italic", width=24))
```

<img width="487" alt="image" src="https://user-images.githubusercontent.com/17436313/165038976-5b0936d7-6cdc-4e93-8e7e-48f76781e72a.png">

**Comment by FedeClaudi** [comment]
Sorry for the delay with this... 

The next version of Term will have an improved `truncate` function (which is what cut's the title short there):
```Julia
julia> tprint(Panel(title="12345678: [italic]abcdefg[/italic]", width=20))
╭──── 12345678:... ╮
╰──────────────────╯
```
