### ISSUE TITLE
Can I print a table?

### ISSUE THREAD

**Issue by eschnett** [FedeClaudi/Term.jl#83]
I have a table (with about 5 columns and 20 rows) of strings. I want to output this in a nice format where I don't have to manually choose how wide each column needs to be etc. Can I do this with Term.jl?

That is, I don't want a horizontally or vertically stacked layout, I want a layout that has a regular pattern in 2D.

**Comment by YongHee-Kim** [comment]
You can use [PrettyTables.jl](https://ronisbr.github.io/PrettyTables.jl/stable/man/usage/#Examples) with Term. 

``` julia
data = [1 2 3; 4 5 6]
tb = pretty_table(String, data; header = ["Column 1", "Column 2", "Column 3"])

a = Term.RenderableText(tb)
b = Term.RenderableText("this is some string")
c = Term.Panel("What a day!", width=15)

print((a * c) / (c * b))

┌──────────┬──────────┬──────────┐╭─────────────╮
│ Column 1 │ Column 2 │ Column 3 ││  What a     │
├──────────┼──────────┼──────────┤│  day!       │
│        1 │        2 │        3 │╰─────────────╯
│        4 │        5 │        6 │
└──────────┴──────────┴──────────┘

╭─────────────╮this is some string
│  What a     │
│  day!       │
╰─────────────╯

```

**Comment by FedeClaudi** [comment]
I didn't know about PrettyTables, awesome!

In due time Term will have it's own table functionality supporting coloring etc, but I kinda need to finish my PhD first and then I'll have the time for it 👍🏻

**Comment by FedeClaudi** [comment]
Closing this as the original question was answered, but keep an eye out for future developments!
