### ISSUE TITLE
Progress bar style and colors get messed up when using Term.jl on Julia through `screen` on SSH

### ISSUE THREAD

**Issue by ultrapoci** [FedeClaudi/Term.jl#85]
I'm currently running Julia through SSH, and I'm using `screen` to keep the session opened when disconnecting from SSH. 
I've noticed that if I use Term's progress bar on SSH *without* `screen`, everything works fine. If I instead launch Julia after having launched `screen`, the progress bar looks like this:
![image](https://user-images.githubusercontent.com/50493113/167847740-9261be43-b24a-4350-96e7-ca4f8a62f1c2.png)

Don't mind the multiple headers, that was my fault for having resized the window. But the underline of the info logs, and all the weird colors, are due to the fact that I'm using Term behind `screen`. All other colors in the REPL (provided by OhMyREPL.jl) look perfectly fine, it's only Term's colors that are messed up. 

I'm using Windows Terminal with Julia v1.7.2 and Term 0.3.0.

**Comment by FedeClaudi** [comment]
Hey, thanks for sending this in. I don't know what `screen` is or what it does, so I'll have to do some digging to figure out what's happening here.
