### ISSUE TITLE
Panel content centering and title style

### ISSUE THREAD

**Issue by nathanrboyer** [FedeClaudi/Term.jl#91]
With the code below, the top-right corner of the main Panel and its title are not colored. This is fixed if I uncomment the `title_style` line.

Additionally, I wanted `justify = :center` to center the entire top half of the main Panel but it has not effect.

```julia
julia> function tableKM620_options()
           material_option_numbers = RenderableText(join(string.(collect(1:nrow(tableKM620))), "\n"))
           tableKM620_materials_string = RenderableText(join(tableKM620."Material", "\n"))
           tableKM620_note_string = RenderableText("Ferritic steel includes carbon, low alloy, and alloy steels,\nand ferritic, martensitic, and iron-based age-hardening stainless steels.")   
           vline = vLine(material_option_numbers, style = "cyan")
           material_note = Panel(tableKM620_note_string,
                                   title = "Note",
                                   style = "cyan",
                                   fit = true)
           options_panel = Panel(material_option_numbers * " " * vline * " " * tableKM620_materials_string / " ", material_note,
                                   title = "Table KM-620 Options",
                                   #title_style = "cyan bold",
                                   style = "cyan bold",
                                   justify = :center,
                                   title_justify = :center,
                                   fit = true)
           return options_panel
       end
tableKM620_options (generic function with 1 method)

julia> tableKM620 = DataFrame("Material" => ["Ferritic steel",
                                        "Austenitic stainless steel and nickel-based alloys",
                                        "Duplex stainless steel",
                                        "Precipitation hardening, nickel based",
                                        "Aluminum",
                                        "Copper",
                                        "Titanium and zirconium"])
7×1 DataFrame
 Row │ Material
     │ String
─────┼───────────────────────────────────
   1 │ Ferritic steel
   2 │ Austenitic stainless steel and n…
   3 │ Duplex stainless steel
   4 │ Precipitation hardening, nickel …
   5 │ Aluminum
   6 │ Copper
   7 │ Titanium and zirconium

julia> tprint(tableKM620_options())
╭────────────────────────────── Table KM-620 Options ───────────────────────────────╮[/cyan bold]
│  1 │ Ferritic steel                                                               │
│  2 │ Austenitic stainless steel and nickel-based alloys                           │
│  3 │ Duplex stainless steel                                                       │
│  4 │ Precipitation hardening, nickel based                                        │
│  5 │ Aluminum                                                                     │
│  6 │ Copper                                                                       │
│  7 │ Titanium and zirconium                                                       │
│                                                                                   │
│  ╭──── Note ───────────────────────────────────────────────────────────────────╮  │
│  │  Ferritic steel includes carbon, low alloy, and alloy steels,               │  │
│  │  and ferritic, martensitic, and iron-based age-hardening stainless steels.  │  │
│  ╰─────────────────────────────────────────────────────────────────────────────╯  │
╰───────────────────────────────────────────────────────────────────────────────────╯

**Comment by FedeClaudi** [comment]
HI, 

Thanks for getting in touch.

That seems to be a bug with the way the title line of the panel is created, will fix asap. 

For the centering, that's not how it currently works:

```Julia

using Term

small = Panel(; width=20)
large = Panel(; width=50)

print(Panel(small/large; fit=false, justify=:center))
```
gives:
```
╭──────────────────────────────────────────────────────────────────────────────────────╮
│                  ╭──────────────────╮                                                │
│                  ╰──────────────────╯                                                │
│                  ╭────────────────────────────────────────────────╮                  │
│                  ╰────────────────────────────────────────────────╯                  │
╰──────────────────────────────────────────────────────────────────────────────────────╯
```

and that's because `small / large` creates a new renderable with `width=50` and the entire renderable is centered within the panel. Information about the individual panels is lost by that point so the `justify=:center` cannot justify each sub-panel. 

So currently you'd have to stack the subpanels in a way where the top panel is already centered:

```Julia
using Term
import Term.layout: Spacer

small = Panel(; width=20)
space = Spacer(15, 2)

large = Panel(; width=50)

print(Panel((space * small * space) / large; fit=false, justify=:center))

╭──────────────────────────────────────────────────────────────────────────────────────╮
│                                 ╭──────────────────╮                                 │
│                                 ╰──────────────────╯                                 │
│                  ╭────────────────────────────────────────────────╮                  │
│                  ╰────────────────────────────────────────────────╯                  │
╰──────────────────────────────────────────────────────────────────────────────────────╯
```


This is a bit tedious though, so I think I should add versions of `vstack` and `hstack` that let users specify how things should be justified so that you can do something like: `vstack(small, large; justify=:center)` to get what you need.

**Comment by FedeClaudi** [comment]
The title style bug will be fixed in next release - and the release will also include versions of `vstack`/`hstack` which allow for centering. I'll notify you when this comes out.

**Comment by FedeClaudi** [comment]
The next version will have code to left/right align and center two renderables: https://github.com/FedeClaudi/Term.jl/blob/545345c44a90eb0eb4ba91334a5945f87616c1d3/src/layout.jl#L148

with also three shorthand notation function: `⊏, ⊐, ⊔` (left, right, center) which can be combined with the stacking function:

```Julia

p1 = Panel(; width=25)
p2 = Panel(; width=50)

print(
    ⊐(p1,  p2) |> /
  )

                         ╭───────────────────────╮
                         ╰───────────────────────╯
╭────────────────────────────────────────────────╮
╰────────────────────────────────────────────────╯
```


I'm not very happy with the syntax, but the idea is that you can combine justification with stacking to get the result you're looking for.

**Comment by FedeClaudi** [comment]
Here's the docs: https://fedeclaudi.github.io/Term.jl/dev/basics/content_layout/#Justify

**Comment by nathanrboyer** [comment]
Functionality is great, but the syntax is unfortunate. I tried to work out something better with [function composition](https://docs.julialang.org/en/v1/manual/functions/#Function-composition-and-piping), but that only seems to work with unary operators. I will probably go with the first method suggested in the docs:
```julia
p1, p2 = rightalign(p1, p2)
print(p1/p2)
```
Maybe a modifying version would be convenient?
```julia
rightalign!(p1, p2)
print(p1/p2)
```

**Comment by FedeClaudi** [comment]
Yeah, I'm not very happy with the syntax too. 

Perhaps the best way is to provide additional functions that directly combine justification with vertical stacking: `leftstack`, `centerstack`, `rightstack`... but it starts becoming a lot of function names to remember. I would like to come up with a clever syntax that reduces cognitive load on the user...


My hesitation with the modifying version of these functions is that they potentially change the type of the renderable, though there might be a way to avoid that perhaps...


I'm happy the functionality is good, not I need to come with something clever to make it more intuitive to use!

**Comment by FedeClaudi** [comment]
The next version will have `centering`, `leftalign`, and `rightalign` to do the alignment alone or `cvstack`, `lvstack`, `rvstack` to simultaneously align and vertically stack renderables.
