### ISSUE TITLE
User input not visible while using ProgressBar.

### ISSUE THREAD

**Issue by nathanrboyer** [FedeClaudi/Term.jl#96]
I imagine this may be difficult to fix, but it would be nice if I could collect user input and use `ProgressBar` at the same time. Presently, the first letter of the current line is overwritten. The data is processed correctly, but it is hard for the user to see what they have typed.

(Also, is there a better way to get a variable like `user_input` out of the `do` block than the `global` keyword?)

```julia
function get_user_input()
    print("What is your name? ")
    return readline()
end

function main()
    progressbar = ProgressBar(; columns=:minimal, columns_kwargs = Dict(:SpinnerColumn => Dict(:spinnertype => :circle)))
    with(progressbar) do
        inputjob = addjob!(progressbar, description = "Gathering User Input")
        start!(inputjob)
        global user_input = get_user_input()
        stop!(inputjob)
    end
    return user_input
end
```
```julia
julia> main()

nhat is your name?


─────────────────────────────── progress ───────────────────────────────
Gathering User Input ✔
"Nathan"
```

**Comment by nathanrboyer** [comment]
That works. You lose the spinning, but I guess that's okay.
```julia
julia> function get_user_input(progressbar)
           sleep(1)
           progressbar.running = false
           print("What is your name? ")
           user_input = readline()
           progressbar.running = true
           return user_input
       end
get_user_input (generic function with 1 method)

julia> function main()
           progressbar = ProgressBar(; columns=:minimal, columns_kwargs = Dict(:SpinnerColumn => Dict(:spinnertype => :circle)))
               stop!(inputjob)
               return user_input
           end
           return user_input
       end
main (generic function with 1 method)

julia> main()









What is your name? Nathan


─────────────────────────────────── progress ───────────────────────────────────
Gathering User Input ✔
"Nathan"
```

**Comment by FedeClaudi** [comment]
I think there might be something missing from your example code? The progress bar is not started etc...

> That works. You lose the spinning, but I guess that's okay.

Indeed, not ideal but I guess it should only be for a little bit while the user provides the input.
I'd be curious to know in what circumstances one would like to have progress bars and user input at the same time!

**Comment by nathanrboyer** [comment]
Whoops, the function definitions above are supposed to be:
```julia
using Term.progress

function get_user_input(progressbar)
    sleep(1)
    progressbar.running = false
    print("What is your name? ")
    user_input = readline()
    progressbar.running = true
    return user_input
end

function main()
    progressbar = ProgressBar(; columns=:minimal, columns_kwargs = Dict(:SpinnerColumn => Dict(:spinnertype => :circle)))
    user_input = with(progressbar) do
        inputjob = addjob!(progressbar, description = "Gathering User Input")
        start!(inputjob)
        user_input = get_user_input(progressbar)
        stop!(inputjob)
        return user_input
    end
    return user_input
end
```

This shows a separate issue I am having where the progress bar chops off some lines when I scroll back up in the REPL

**Comment by nathanrboyer** [comment]
> I'd be curious to know in what circumstances one would like to have progress bars and user input at the same time!

Admittedly, this is not a very important use case. I only considered it because `get_user_input` is the only function in my actual code without a progress job, and I thought the code would look nicer if that function call was also inside the `do` block. 😄 
```julia
function main()
    global user_input = get_user_input()

    progressbar = ProgressBar(; columns=:minimal, columns_kwargs = Dict(:SpinnerColumn => Dict(:spinnertype => :circle)))
    with(progressbar) do
        readjob = addjob!(progressbar, description = "Reading Input File")
        start!(readjob)
        global ASME_tables, ASME_groups = read_ASME_tables(user_input)
        stop!(readjob)

        transformjob = addjob!(progressbar, description = "Transforming Tables")
        start!(transformjob)
        global ANSYS_tables = transform_ASME_tables(ASME_tables, ASME_groups, user_input)
        stop!(transformjob)

        writejob = addjob!(progressbar, description = "Writing Output Tables")
        start!(writejob)
        write_ANSYS_tables(ANSYS_tables, user_input)
        stop!(writejob)

        plotjob = addjob!(progressbar, description = "Plotting Results")
        start!(plotjob)
        global fig_tc, fig_te, fig_ym, fig_ps = plot_ANSYS_tables(ANSYS_tables, user_input)
        display(fig_ps)
        stop!(plotjob)
    end
end
```

**Comment by FedeClaudi** [comment]
makes sense! and without the `global` there `user_input` would not be visible within the `do` code? Or is there for some other reason?

**Comment by nathanrboyer** [comment]
`user_input` enters the `do` block okay without `global`. I am just trying to return all the calculated variables from `main`. If I, for example, put `return ANSYS_tables` at the end of `main`, then I get `ERROR: UndefVarError: ANSYS_tables not defined` without the `global` keyword.  `global` was a quick way to get everything out, but I am still exploring other options.

**Comment by FedeClaudi** [comment]
julia's scoping rules still give me headaches sometimes... 
Perhaps the best way would be to have `fig_tc, fig_te, fig_ym, fig_ps` as the last line of the `do` block, similarly to what we discussed above. I'm not sure if then you also need to do `fig_tc, fig_te, fig_ym, fig_ps = with(pbar) do...`.
That looks a bit ugly but may be safer than setting global variables. 


By the way I really appreciate you trying out `Term.jl` is such detail and always providing detailed reports and updates, including walking me through your user case. The feedback you've provided has already helped improving Term a lot!

**Comment by nathanrboyer** [comment]
I think that would work, but then I would have to call `main` with `(user_input, ASME_tables, ASME_groups, ANSYS_tables, fig_tc, fig_te, fig_ym, fig_ps) = main();` (`;` to avoid dumping a mess under my pretty `Term` output!). I want to just type `main()` 😞 

Thank **you**! It's a great package and you have been very quick to respond to my issues.

**Comment by FedeClaudi** [comment]
yep that's true, you'd have to get them out of `main` too!

I don't think I'll be working on user inputs any time soon and this seems like an acceptable fix for what's probably a relatively rare edge case of progress bar usage. Happy for me to close it with the solution provided above?

**Comment by nathanrboyer** [comment]
Yep!

Btw, I got a decent solution for the scope issue figured out already.
```julia
# Output Struct
struct ASME_Materials_Data
    user_input
    ASME_tables
    ASME_groups
    ANSYS_tables
    fig_tc
    fig_te
    fig_ym
    fig_ps
end

# Full Program
function main()
    user_input = get_user_input()

    progressbar = ProgressBar(; columns=:minimal, columns_kwargs = Dict(:SpinnerColumn => Dict(:spinnertype => :circle)))
    output = with(progressbar) do
        readjob = addjob!(progressbar, description = "Reading Input File")
        start!(readjob)
        ASME_tables, ASME_groups = read_ASME_tables(user_input)
        stop!(readjob)

        transformjob = addjob!(progressbar, description = "Transforming Tables")
        start!(transformjob)
        ANSYS_tables = transform_ASME_tables(ASME_tables, ASME_groups, user_input)
        stop!(transformjob)

        writejob = addjob!(progressbar, description = "Writing Output Tables")
        start!(writejob)
        write_ANSYS_tables(ANSYS_tables, user_input)
        stop!(writejob)

        plotjob = addjob!(progressbar, description = "Plotting Results")
        start!(plotjob)
        fig_tc, fig_te, fig_ym, fig_ps = plot_ANSYS_tables(ANSYS_tables, user_input)
        display(fig_ps)
        stop!(plotjob)

        ASME_Materials_Data(user_input, ASME_tables, ASME_groups, ANSYS_tables, fig_tc, fig_te, fig_ym, fig_ps)
    end

    print("\n", goodbye_message(user_input.output_file_path))
    return output
end
```

```julia
julia> main();

julia> x = ans; # If needed

julia> display(x.fig_tc) # Example
```
