### ISSUE TITLE
concise information

### ISSUE THREAD

**Issue by t-bltg** [FedeClaudi/Term.jl#99]
I believe that https://github.com/FedeClaudi/Term.jl/blob/613502b5ca4cea2cacdf4dac0d81c5e24a3a8f05/src/renderables.jl#L39
 should be renamed to something like `info(renderable::AbstractRenderable)`, or maybe it's definition should be swapped with `Base.show(io::IO, renderable::AbstractRenderable)`, allowing to render the panel in the repl instead of something akin to Python's `repr` for debugging.

This (definitions swapped) feels more natural when working withing the repl:
```julia
julia> Panel("foo")
╭──────────────────────────────────────────────────────────────────────────────────────╮
│  foo                                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────╯
julia> show(io, Panel("foo"))
Panel <: AbstractRenderable size: Measure (w: 88, h: 3)
```

Has this been discussed somewhere ?

**Comment by FedeClaudi** [comment]
Great timing, I just made a comment about this in the PR you've just opened. 
It took me a while to wrap my head around it (see here: https://github.com/FedeClaudi/Term.jl/issues/82#issuecomment-1133418461) but now it works as you suggested (from the next release in a couple weeks):

```Julia
<img width="410" alt="image" src="https://user-images.githubusercontent.com/17436313/170836849-41c739d6-2dcd-4b7a-b66e-00ae705b23f0.png">
```

**Comment by t-bltg** [comment]
Thanks, I checked out `v4` and using `display(Panel("foo"))` is outputting exactly what I was expecting (from a code not evaluated in the REPL).

**Comment by FedeClaudi** [comment]
Awesome, the next version will have a couple breaking changes (which shouldn't affect you thought) but also a lot of new/improved things like these. 

If you're working on layout stuff for unicode plots I'd be curious to see what comes out of it! Currently `Term` is less than ideal in e.g. accounting for the terminal width etc. It might also be nice to have a `grid(renderables...` function that creates a grid layout from a bunch of renderables!

**Comment by t-bltg** [comment]
> If you're working on layout stuff for unicode plots I'd be curious to see what comes out of it!

I am currently trying to remove most of the `Plots` calls in my old codes, and replacing them with `UnicodePlots` + `Term` for the layout.

Here on a simple cavity flow, it looks nice, although I'd be nice if the `Term.renderables.Renderable <: AbstractRenderable (w:119, h:40)` was made optional, but I can live with it ;)

![cavity](https://user-images.githubusercontent.com/13423344/170838863-6975ec54-01c3-4824-adff-990acd0b3bd7.png)

Ha yes, `grid` would be awesome, I'll try something out now.

**Comment by FedeClaudi** [comment]
That looks great! The line at the bottom comes up when using `display`? 

Admittedly it's not very useful in this case, but it can be when prototyping a layout with multiple renderables and has a didactic value when it comes up in the documentation. 

What would be the best way to make it optional? I'm guessing `display` calls `show` here, but [which version](https://github.com/FedeClaudi/Term.jl/blob/27837e44bf3e7fa37df86a23719fcc3fc377315c/src/renderables.jl#L49) ?

Perhaps there's a way to remove the line when using `display` vs just showing a renderable in the REPL.

**Comment by t-bltg** [comment]
> The line at the bottom comes up when using display?

Yes, because `REPLDisplay` uses `show` with `"text/plain"` mime when defining `display`: https://github.com/JuliaLang/julia/blob/eb230a55d2bb075b6c77391866bf4816fac718f5/stdlib/REPL/src/REPL.jl#L267.

> I'm guessing display calls show here, but [which version](https://github.com/FedeClaudi/Term.jl/blob/27837e44bf3e7fa37df86a23719fcc3fc377315c/src/renderables.jl#L49) ?

It's this one https://github.com/FedeClaudi/Term.jl/blob/27837e44bf3e7fa37df86a23719fcc3fc377315c/src/renderables.jl#L68
, because `"text/plain"` specializes the generic one.

> What would be the best way to make it optional?

I'd have to think about that. Everything boils down to `show(...)` so I feel we're a bit stuck here, unless using a dedicated function for that purpose. I always reason in terms on simplicity for the end user. So the minimalistic version is to let the `REPLDisplay` handle the `display` call under the hood in the `REPL`, and use the high level `display` in scripts otherwise.

**Comment by FedeClaudi** [comment]
thank's for the info. Yeah I don't think another function is necessary. perhaps just a `global` flag (set to `false` by default) which determines if we should print the extra line? Passing arguments to `show` might be hard...

**Comment by t-bltg** [comment]
Yes, something like `const DEBUG = Ref(false)`, in order to be able to toggle the flag if needed.

**Comment by FedeClaudi** [comment]
https://github.com/FedeClaudi/Term.jl/pull/102/ adds this behavior:

<img width="556" alt="image" src="https://user-images.githubusercontent.com/17436313/170872452-9fef07e2-2071-4b03-b8bf-e95a824bbe6d.png">

where `const TERM_DEBUG_ON = Ref(false)`. I understand the motivation for using `Ref`, but I have to admit I'm not a big fan of the syntax since its value is then accessed/modified with `TERM_DEBUG_ON[]`, but I'll live with it for now.
